name: Fichaje prueba 30min

on:
  schedule:
    # Inicio ficticio 09:50 UTC (10:50 España)
    - cron: '50 9 * * 5'
    # Stop 09:55 UTC (10:55 España)
    - cron: '55 9 * * 5'
  workflow_dispatch:
    inputs:
      mode:
        description: 'start o stop'
        required: true
        default: 'stop'

jobs:
  fichaje:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install requests
        run: pip install requests

      - name: Ejecutar fichaje
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            python fichaje.py ${{ github.event.inputs.mode }}
          else
            HOUR=$(date -u +"%H:%M")
            DAY=$(date -u +"%u")

            if [[ "$DAY" -eq 5 && "$HOUR" == "09:50" ]]; then
              python fichaje.py start
            elif [[ "$DAY" -eq 5 && "$HOUR" == "09:55" ]]; then
              python fichaje.py stop
            fi
          fi
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}

