name: Fichaje STOP

on:
  schedule:
    # Lunes a Jueves a las 18:00 España (17:00 UTC)
    - cron: '0 17 * * 1-4'
    # Viernes a las 15:00 España (14:00 UTC)
    - cron: '0 14 * * 5'
  workflow_dispatch:

jobs:
  stop_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install requests
        run: pip install requests
      - name: Ejecutar Stop
        run: python fichaje.py stop
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
