name: Fichaje START

on:
  schedule:
    # Lunes a Jueves a las 08:30 España (07:30 UTC)
    - cron: '30 7 * * 1-4'
    # Viernes a las 08:00 España (07:00 UTC)
    - cron: '0 7 * * 5'
  workflow_dispatch:

jobs:
  start_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install requests
        run: pip install requests
      - name: Ejecutar Start
        run: python fichaje.py start
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
