name: TEST Stop 12:20

on:
  schedule:
    # 12:20 Espa√±a es 11:20 UTC
    - cron: '20 11 * * *'
  workflow_dispatch:

jobs:
  test_stop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install requests
        run: pip install requests
      - name: Ejecutar Stop Prueba
        run: python fichaje.py stop
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          
