name: TEST Start 12:15

on:
  schedule:
    # 12:15 Espa√±a es 11:15 UTC
    - cron: '15 11 * * *'
  workflow_dispatch:

jobs:
  test_start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install requests
        run: pip install requests
      - name: Ejecutar Start Prueba
        run: python fichaje.py start
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
